version: '3'

services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - theHarvester
      - Amass

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: domain_enumeration
    volumes:
      - postgres_data:/var/lib/postgresql/data

  theHarvester:
    build: theHarvester

  Amass:
    build: Amass

volumes:
  postgres_data: